#! /bin/sh

set -e

# On server:
# $ iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8000
# Or use authbind:
# $ cd www
# $ screen
# $ authbind ~/bin/homepage-server -p 80
# C-a d

cd server
#cabal build
#strip -s dist/build/server/server
rsync -e ssh -varuzP dist-newstyle/build/x86_64-linux/ghc-8.0.2/server-0.1/build/server/server coldwaste:bin/homepage-server
cd ..

cd content
rm _site/js || true
ln -s ../js _site/js
rsync -e ssh -varuzPL _site/ coldwaste:www/static
cd ..
