#! /bin/sh

# On server:
# iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8000
# Or use authbind

cd server
cabal build
strip -s dist/build/server/server
rsync -e ssh -varuzP dist/build/server/server www@coldwaste:bin/homepage-server
cd ..

cd content
make all
ln -s ../js _site/js
rsync -e ssh -varuzPL _site/ www@coldwaste:www/static
cd ..
